services:
  authkeycloak:
    image: ${DOCKER_REGISTRY-}authkeycloak
    build:
      context: .
      dockerfile: AuthKeycloak/Dockerfile
    networks:
      - keycloak-network
    ports:
      - "3000:8080"
  
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:26.0.8
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: token-exchange,admin-fine-grained-authz,declarative-ui
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network
    command:
      - start-dev

networks:
  keycloak-network:

volumes:
  postgres_data: